version: '3.4'

services:
  integrationtest.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44363
    ports:
      - "55699:80"
      - "44363:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  sql-data-test:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  integrationtest.test:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql-data-test;Initial Catalog=integrationtestDb.test;User Id=sa;Password=Pass@word;
    ports:
      - "5101:80"
    entrypoint:
      - dotnet
      - test
      - -c
      - ${BUILD_CONFIGURATION}
      - --no-build
      - --no-restore
      - --logger
      - trx;LogFileName=/tests/services-test-results.trx